FROM hectorqin/reader

ENV TZ=Asia/Shanghai
ENV SPRING_PROFILES_ACTIVE=prod
ENV READER_APP_USERLIMIT=""
ENV READER_APP_USERBOOKLIMIT=""
ENV READER_APP_CACHECHAPTERCONTENT=""
ENV READER_APP_SECURE=""
ENV READER_APP_SECUREKEY=""
ENV READER_APP_INVITECODE=""

EXPOSE 8080
ENTRYPOINT ["/sbin/tini", "--"]
CMD ["java", "-jar", "/app/bin/reader.jar" ]
